---
- block:
  - name: Check if Zabbix Agent 2 is already installed
    shell: dpkg -l | grep "zabbix-agent2 .*"
    register: zabbix_agent2_installed
    ignore_errors: true

  - name: Debug the Zabbix Agent 2 installation status
    debug:
      msg: "Zabbix Agent 2 is already installed!"
    when: zabbix_agent2_installed.rc == 0
  become: true

- block:
  - name: Ensure apt cache is up-to-date
    apt:
      update_cache: yes

  - name: Download Zabbix repository package
    get_url:
      url: "https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_7.0-1+ubuntu{{ ansible_distribution_version }}_all.deb"
      dest: /tmp/zabbix-release.deb

  - name: Install Zabbix repository package
    command: dpkg -i /tmp/zabbix-release.deb

  - name: Update apt cache after adding Zabbix repository
    apt:
      update_cache: yes

  - name: Install Zabbix Agent 2
    apt:
      name: zabbix-agent2
      state: present

  - name: Add zabbix server to zabbix_agent2.conf for passive
    shell: sed -i "s/^Server=.*/Server={{ zabbix_server }}/" /etc/zabbix/zabbix_agent2.conf

  - name: Add zabbix server to zabbix_agent2.conf for active
    shell: sed -i "s/^ServerActive=.*/ServerActive={{ zabbix_server }}/" /etc/zabbix/zabbix_agent2.conf

  - name: Add hostname to zabbix_agent2.conf
    shell: sed -i "s/^Hostname=.*/Hostname=$(hostname)/" /etc/zabbix/zabbix_agent2.conf

  - name: Add metadata to zabbix_agent2.conf
    shell: sed -i "s/^# HostMetadata=.*/HostMetadata=Linux/" /etc/zabbix/zabbix_agent2.conf

  - name: Add docker group for zabbix user
    shell: usermod -aG docker zabbix

  - name: Ensure Zabbix Agent 2 is enabled and started
    service:
      name: zabbix-agent2
      enabled: yes
      state: restarted
  when: zabbix_agent2_installed.rc != 0
  become: true